"""empty message

Revision ID: b4e0392dba31
Revises: 61feabd77013
Create Date: 2022-10-05 18:55:04.923794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e0392dba31'
down_revision = '61feabd77013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'players', ['account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    # ### end Alembic commands ###
