"""empty message

Revision ID: 61feabd77013
Revises: 1b436c7f7800
Create Date: 2022-10-05 17:56:31.638901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61feabd77013'
down_revision = '1b436c7f7800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_name_key', 'cards', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cards_name_key', 'cards', ['name'])
    # ### end Alembic commands ###
